server:
  port: 9999
  servlet:
    context-path: /
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
    template-resolver-order: 0
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/~/h2database/board
    username: octavia
    password:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
logging:
  level:
    org.hibernate.sql: debug


application:
  storage-path : D://Temp/octavina-board